[package]
name = "geo-uri"
version = "0.1.0"
authors = ["Paul van Tilburg <paul@luon.net>"]
edition = "2021"
description = "A Rust crate for parsing uniform resource identifiers for geographic locations (geo URIs)"
readme = "README.md"
license = "MIT"

[dependencies]
derive_builder = "0.11.2"
thiserror = "1.0.35"

[dev-dependencies]
float_eq = "1.0.0"
