[package]
name = "geo-uri"
version = "0.1.0"
authors = ["Paul van Tilburg <paul@luon.net>"]
edition = "2021"
description = "A crate for parsing and generating uniform resource identifiers for geographic locations (geo URIs)"
homepage = "https://git.luon.net/paul/geo-uri-rs"
repository = "https://git.luon.net/paul/geo-uri-rs.git"
readme = "README.md"
license = "MIT"
keywords = ["geolocation", "uri", "parser", "rfc5870"]

[dependencies]
derive_builder = "0.11.2"
thiserror = "1.0.35"

[dev-dependencies]
float_eq = "1.0.0"
