[package]
name = "geo-uri"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.11.2"
thiserror = "1.0.35"

[dev-dependencies]
float_eq = "1.0.0"
